<?php

ob_start();

// Cache dosyası ve süre
$cacheFile = 'cache/' . urlencode($clanTag) . '.json';
$cacheTime = 3000; // 50 dakika = 3000 saniye

// Clash of Clans API anahtarınızı buraya ekleyin
$apiKey = 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6IjJiOTBkODViLTAxNzAtNDg3OS1iNDVlLWExNDliZjdlZmY1MCIsImlhdCI6MTcyMzEyNzE3Nywic3ViIjoiZGV2ZWxvcGVyL2UzZmZjOTdjLTkzNDItMzQxZi1kY2ZiLWI4YzY5MTU3NTQ3OSIsInNjb3BlcyI6WyJjbGFzaCJdLCJsaW1pdHMiOlt7InRpZXIiOiJkZXZlbG9wZXIvc2lsdmVyIiwidHlwZSI6InRocm90dGxpbmcifSx7ImNpZHJzIjpbIjMxLjE4Ni4xMS4xMTMiXSwidHlwZSI6ImNsaWVudCJ9XX0.FwxMBOWF3tz9V5SH6ChNfv7JlEzhdtQ3H4xe9DDhwkgfmSzf-h63ammFtGUBzxD2bmVAWF88uYVz8N3i4gEBXw';

// Almak istediğiniz klanların taglerini buraya ekleyin
$clanTags = ['#GPGPCLJJ', '#QLVROLCC', '#P9LJC89Y', '#990JORL2', '#8P2QG08P', '#2Y8G2PU2P', '#89R889VG', '#2PC2C8YU0', '#802ULYR2', '#V2Y8YVLC', '#LY2RGCYU', '#UUQ00JL2', '#YJRCGJ9Y', '#JVVRLG0', '#8U8U2V2L', '#2V20YLQU', '#PYPC00JC', '#VVJCY9J', '#2Q9GCVJ8U', '#RYPU0G2C', '#2PJLJ8Q0G', '#P98QRCYL', '#L0RJJ0GU', '#PCP0CQJG', '#PRBC9JRL', '#2CVPQRL9', '#G0Q80CR9', '#C9YVPLL9', '#YYCLQYJL', '#20UYV9GCR', '#29LJ8PG8G', '#989J0YY0', '#YGUCR8GG', '#22CJBUJVY', '#29RCG2VGP', '#8P0PRC9L', '#29L20PJVU', '#V0R2L90J', '#2QQL0YLGV', '#L0UGCJC9', '#2Q82GC0VU', '#2QYPU299U', '#2YGGJJL9C', '#2P29G9L9C', '#JGYGGUQ2', '#Q8ZY029R', '#LGV0CCRR', '#Q09VJJR8', '#2QG2GL9V9'];

// Check if cache exists and is still valid
if (file_exists($cacheFile) && (time() - filemtime($cacheFile)) < $cacheTime) {
        $clansData = json_decode(file_get_contents($cacheFile), true);
} else {
        // Çoklu istekleri paralel yapmak için kullanılacak fonksiyon
            function getClansData($clanTags, $apiKey) {
                        $clans = [];
                                $multiHandle = curl_multi_init();
                                        $handles = [];
                                        foreach ($clanTags as $clanTag) {
                                                        $url = "https://api.clashofclans.com/v1/clans/" . urlencode($clanTag);
                                                                    $headers = [
                                                                                    "Authorization: Bearer " . $apiKey,
                                                                                                ];

                                                                                                            $ch = curl_init();
                                                                                                                        curl_setopt($ch, CURLOPT_URL, $url);
                                                                                                                                    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
                                                                                                                                                curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
                                                                                                                                                            curl_multi_add_handle($multiHandle, $ch);
                                                                                                                                                                        $handles[$clanTag] = $ch;
                                                                                                                                                                                }

                                                                                                                                                                                        $active = null;
                                                                                                                                                                                                do {
                                                                                                                                                                                                            curl_multi_exec($multiHandle, $active);
                                                                                                                                                                                                                        curl_multi_select($multiHandle);
                                                                                                                                                                                                                                } while ($active && curl_multi_select($multiHandle) != -1);

                                                                                                                                                                                                                                        foreach ($handles as $clanTag => $ch) {
                                                                                                                                                                                                                                                    $response = curl_multi_getcontent($ch);
                                                                                                                                                                                                                                                                $clans[$clanTag] = json_decode($response, true);
                                                                                                                                                                                                                                                                            curl_multi_remove_handle($multiHandle, $ch);
                                                                                                                                                                                                                                                                                        curl_close($ch);
                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                        curl_multi_close($multiHandle);

                                                                                                                                                                                                                                                                                                                return $clans;
                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                        $clansData = getClansData($clanTags, $apiKey);

                                                                                                                                                                                                                                                                                                                            // Cache the clans data
                                                                                                                                                                                                                                                                                                                                file_put_contents($cacheFile, json_encode($clansData));
                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                // Üyelerin toplam bağışlarını ve diğer bilgileri hesaplayan fonksiyonlar
                                                                                                                                                                                                                                                                                                                                function calculateTotalDonations($clan) {
                                                                                                                                                                                                                                                                                                                                    $totalDonations = 0;
                                                                                                                                                                                                                                                                                                                                        if (isset($clan['memberList'])) {
                                                                                                                                                                                                                                                                                                                                                foreach ($clan['memberList'] as $member) {
                                                                                                                                                                                                                                                                                                                                                            $totalDonations += $member['donations'];
                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                            return $totalDonations;
                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                            function calculateTotalReceived($clan) {
                                                                                                                                                                                                                                                                                                                                                                                if (isset($clan['memberList'])) {
                                                                                                                                                                                                                                                                                                                                                                                        return array_sum(array_column($clan['memberList'], 'donationsReceived'));
                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                return 0;
                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                function getClanLeader($clan) {
                                                                                                                                                                                                                                                                                                                                                                                                    if (isset($clan['memberList'])) {
                                                                                                                                                                                                                                                                                                                                                                                                            foreach ($clan['memberList'] as $member) {
                                                                                                                                                                                                                                                                                                                                                                                                                        if ($member['role'] === 'leader') {
                                                                                                                                                                                                                                                                                                                                                                                                                                        return $member['name'];
                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return 'Unknown Leader';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Klanları toplam bağışa göre sıralama
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    usort($clansData, function ($a, $b) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return calculateTotalDonations($b) - calculateTotalDonations($a);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ?>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <html>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <head>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <title>Top Req Clans - Current Season</title>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <style>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        /* CSS styles here, unchanged from your previous code */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        table {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        max-width: 100%; width: 100%;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        border-collapse: collapse;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        th, td {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        padding: 10px;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        text-align: left;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        border-bottom: 1px solid #ddd;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        tr:nth-child(even) {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        background-color: #f2f2f2;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        th {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        background-color: #D3D3D3; /* Krem rengi */
 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        color: #333;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        font-weight: bold;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .first-row {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        background-color: #FFD700; /* Koyu sarı */

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .second-row {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        background-color: #D3D3D3; 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        color: #333;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        /* Gri */

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .third-row {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        background-color: #ADD8E6; /* Mavi */

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .clan-logo {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        max-width: 100%; width: 60px;

                                                                                                                                                                                                                                                                                                                                                                                                                                            

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        vertical-align: middle;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        margin-right: 10px; /* Logo ile metin arasında boşluk oluşturmak için */

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .clan-info {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        display: flex;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        align-items: center;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .clan-info div {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        margin-left: 5px; /* Logo ve metin arasındaki boşluk azaldı */

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .clan-name {


                                                                                                                                                                                                                                                                                                                                                                                                                                                                        font-weight: bold;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        line-height: 1.2; font-size: 20px;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .clan-tag {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        line-height: 1.2; font-size: 0.9em;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        color: #666;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .donations, .received {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        font-weight: bold;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        line-height: 1.2; font-size: 22px;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .leader {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        font-weight: bold;


                                                                                                                                                                                                                                                                                                                                                                                                                                                                        text-align: center; /* Lider sütunundaki metinleri ortalar */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        line-height: 1.2; font-size: 20px;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        a {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        text-decoration: none;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        color: #333;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        a:hover {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        text-decoration: underline;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        @media (max-max-width: 100%; width: 600px) {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        th, td {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        padding: 5px;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        line-height: 1.2; font-size: 12px;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .clan-logo {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        max-width: 100%; width: 60px;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        height: 60px;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .clan-info div {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        margin-left: 5px;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .donations, .received {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        line-height: 1.2; font-size: 22px;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </style>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </head>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <body>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <h1>Top Req Clans - Current Season</h1>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <table>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <thead>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <th>#</th>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <th>Clan</th>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <th class="leader">Leader</th>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <th class="donations">Total Donations</th>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <th class="received">Total Received</th>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </thead>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <tbody>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <?php foreach ($clansData as $index => $clan): ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <?php 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        $totalDonations = calculateTotalDonations($clan); 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        $totalReceived = calculateTotalReceived($clan);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        $leaderName = getClanLeader($clan);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        $rowClass = '';

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if ($index == 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            $rowClass = 'first-row';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } elseif ($index == 1) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $rowClass = 'second-row';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } elseif ($index == 2) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $rowClass = 'third-row';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <tr class="<?= $rowClass ?>">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <td><?= $index + 1 ?></td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <a href="clan.php?tag=<?= urlencode($clan['tag']) ?>" class="clan-info">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <img src="<?= $clan['badgeUrls']['medium'] ?>" alt="Clan Logo" class="clan-logo">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <span class="clan-name"><?= $clan['name'] ?></span><br>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <span class="clan-tag"><?= $clan['tag'] ?></span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <td class="leader"><?= $leaderName ?></td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <td class="donations"><?= number_format($totalDonations) ?></td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <td class="received"><?= number_format($totalReceived) ?></td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <?php endforeach; ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </tbody>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </table>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </body>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </html>
<?php

// Çıkışı yakala
$output = ob_get_clean();

// Gereksiz boşlukları ve satır sonlarını kaldır
$output = preg_replace('/\s+/', ' ', $output);
$output = str_replace('> <', '><', $output);

// Sonuç çıktısını göster
echo $output;
?>
                                        
            }
}
}